# Generated by Django 4.2.11 on 2026-03-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("agent_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OTEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_by_telegram_id", models.BigIntegerField()),
                ("days", models.JSONField(default=list)),
                ("time_slots", models.JSONField(default=dict)),
                ("max_agents", models.PositiveIntegerField(blank=True, null=True)),
                ("is_open", models.BooleanField(default=True)),
                ("group_chat_id", models.BigIntegerField()),
                (
                    "announcement_message_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OTSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=20)),
                ("hours", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "class_type",
                    models.CharField(
                        choices=[
                            ("DIALER", "Dialer"),
                            ("IB", "IB"),
                            ("TOPLIST", "Toplist"),
                        ],
                        max_length=10,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="bot.agent",
                    ),
                ),
                (
                    "ot_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="bot.otevent",
                    ),
                ),
            ],
            options={
                "unique_together": {("agent", "ot_event")},
            },
        ),
    ]
