# Generated by Django 4.2.11 on 2026-03-28 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="otsignup",
            unique_together={("agent", "ot_event", "day")},
        ),
    ]
