# Generated by Django 4.2.11 on 2026-03-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_alter_otsignup_unique_per_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("telegram_username", models.CharField(blank=True, max_length=255)),
                ("telegram_name", models.CharField(blank=True, max_length=255)),
                ("added_by", models.BigIntegerField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="otevent",
            name="deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Auto-close after this UTC datetime (null = no deadline)",
                null=True,
            ),
        ),
    ]
