# Generated by Django 4.2.11 on 2026-04-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_deadline_and_adminuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otsignup",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("DIALER", "Dialer"),
                    ("IB", "IB"),
                    ("TOPLIST", "Toplist"),
                    ("SUPERVISOR", "Supervisor"),
                ],
                max_length=10,
            ),
        ),
    ]
