# Generated by Django 4.2.11 on 2026-04-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_alter_otsignup_class_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="otevent",
            name="disabled_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Day names currently closed to new signups (e.g. ['Monday']). Existing signups for these days are preserved.",
            ),
        ),
    ]
